-- Remaining tables created in later migrations (after init + early timestamptz).
ALTER TABLE "Service" ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3);
ALTER TABLE "Service" ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3);

ALTER TABLE "FamilyService" ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3);

ALTER TABLE "FamilyMember" ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3);
ALTER TABLE "FamilyMember" ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3);

ALTER TABLE "CareSchedule" ALTER COLUMN "startDate" TYPE TIMESTAMPTZ(3);
ALTER TABLE "CareSchedule" ALTER COLUMN "endDate" TYPE TIMESTAMPTZ(3);
ALTER TABLE "CareSchedule" ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3);
ALTER TABLE "CareSchedule" ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3);

ALTER TABLE "Unavailability" ALTER COLUMN "startDate" TYPE TIMESTAMPTZ(3);
ALTER TABLE "Unavailability" ALTER COLUMN "endDate" TYPE TIMESTAMPTZ(3);
ALTER TABLE "Unavailability" ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3);
ALTER TABLE "Unavailability" ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3);

ALTER TABLE "CareSession" ALTER COLUMN "dropOffTime" TYPE TIMESTAMPTZ(3);
ALTER TABLE "CareSession" ALTER COLUMN "pickUpTime" TYPE TIMESTAMPTZ(3);

ALTER TABLE "SessionExpense" ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3);
ALTER TABLE "SessionExpense" ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3);

ALTER TABLE "Expense" ALTER COLUMN "expenseDate" TYPE TIMESTAMPTZ(3);
ALTER TABLE "Expense" ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3);
ALTER TABLE "Expense" ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3);

ALTER TABLE "SessionReport" ALTER COLUMN "timestamp" TYPE TIMESTAMPTZ(3);
ALTER TABLE "SessionReport" ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3);
ALTER TABLE "SessionReport" ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3);

ALTER TABLE "Setting" ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3);
ALTER TABLE "Setting" ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3);
