-- Early tables from init migration only (Service and later tables do not exist yet).
ALTER TABLE "User" ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3);
ALTER TABLE "User" ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3);

ALTER TABLE "Family" ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3);
ALTER TABLE "Family" ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3);

ALTER TABLE "Child" ALTER COLUMN "dateOfBirth" TYPE TIMESTAMPTZ(3);
ALTER TABLE "Child" ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3);
ALTER TABLE "Child" ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3);

ALTER TABLE "CareSession" ALTER COLUMN "scheduledStart" TYPE TIMESTAMPTZ(3);
ALTER TABLE "CareSession" ALTER COLUMN "scheduledEnd" TYPE TIMESTAMPTZ(3);
ALTER TABLE "CareSession" ALTER COLUMN "actualStart" TYPE TIMESTAMPTZ(3);
ALTER TABLE "CareSession" ALTER COLUMN "actualEnd" TYPE TIMESTAMPTZ(3);
ALTER TABLE "CareSession" ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3);
ALTER TABLE "CareSession" ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3);

ALTER TABLE "Payment" ALTER COLUMN "dueDate" TYPE TIMESTAMPTZ(3);
ALTER TABLE "Payment" ALTER COLUMN "paidDate" TYPE TIMESTAMPTZ(3);
ALTER TABLE "Payment" ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3);
ALTER TABLE "Payment" ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3);

ALTER TABLE "Document" ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3);
ALTER TABLE "Document" ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3);
